name: fingerprint-yaml-360-Enterprise-security
manual: false
detail:
    fingerprint:
        name: 360-Enterprise-security
    fofa: body="360entinst" && body="关于全网部署360私有云的通知" && body="私有云控制中心" && body="/download/360inst.exe" || body="360entinst" || body="关于全网部署360私有云的通知" || body="私有云控制中心" || body="/download/360inst.exe" || body="360entinst" && body="关于全网部署360私有云的通知" || body="天擎"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("360entinst") && response.body_string.contains("关于全网部署360私有云的通知") && response.body_string.contains("私有云控制中心") && response.body_string.contains("/download/360inst.exe")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("360entinst")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("关于全网部署360私有云的通知")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("私有云控制中心")
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("/download/360inst.exe")
    r5:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("360entinst") && response.body_string.contains("关于全网部署360私有云的通知")
    r6:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("天擎")
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6()
