name: fingerprint-yaml-360-Total-Security
manual: false
detail:
    fingerprint:
        name: 360-Total-Security
    fofa: header="x-safe-firewall"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("x-safe-firewall"))
expression: r0()
