name: fingerprint-yaml-ALERTMANAGER
manual: false
detail:
    fingerprint:
        name: ALERTMANAGER
    fofa: body="defaultcreator"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("defaultcreator")
expression: r0()
