name: fingerprint-yaml-Amazon Web Services Web Application Firewall(Amazon)
manual: false
detail:
    fingerprint:
        name: Amazon Web Services Web Application Firewall(Amazon)
    fofa: body="Amazon Web Services Web Application Firewall" || body="Amazon" || header="Amazon Web Services Web Application Firewall" || header="Amazon" || title="Amazon Web Services Web Application Firewall" || title="Amazon"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("Amazon Web Services Web Application Firewall")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("Amazon")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Amazon Web Services Web Application Firewall"))
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Amazon"))
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Amazon Web Services Web Application Firewall")
    r5:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Amazon")
expression: r0() || r1() || r2() || r3() || r4() || r5()
