name: fingerprint-yaml-Application Security Manager(F5 Networks)
manual: false
detail:
    fingerprint:
        name: Application Security Manager(F5 Networks)
    fofa: body="Application Security Manager" || body="F5 Networks" || title="Application Security Manager" || title="F5 Networks"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("Application Security Manager")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("F5 Networks")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Application Security Manager")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("F5 Networks")
expression: r0() || r1() || r2() || r3()
