name: fingerprint-yaml-Apusic Application Server
manual: false
detail:
    fingerprint:
        name: Apusic Application Server
    fofa: header="Apusic Application Server" || title="Apusic Application Server"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Apusic Application Server"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Apusic Application Server")
expression: r0() || r1()
