name: fingerprint-yaml-Avaya-Application-Enablement-Services
manual: false
detail:
    fingerprint:
        name: Avaya-Application-Enablement-Services
    fofa: body="<b>application enablement services&nbsp;</b>" || body="avaya" && body="<b>application enablement services&nbsp;</b>" || body="avaya"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<b>application enablement services&nbsp;</b>")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("avaya") && response.body_string.contains("<b>application enablement services&nbsp;</b>")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("avaya")
expression: r0() || r1() || r2()
