name: fingerprint-yaml-BASE
manual: false
detail:
    fingerprint:
        name: BASE
    fofa: body="<!-- Basic Analysis and Security Engine (BASE) -->"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<!-- Basic Analysis and Security Engine (BASE) -->")
expression: r0()
