name: fingerprint-yaml-CETHIK-Reader-Configuration-System
manual: false
detail:
    fingerprint:
        name: CETHIK-Reader-Configuration-System
    fofa: body="if (suser == \"admin\" && spass == \"cetc52\" {" && body="rfid/content/superuser" || body="if suser == \"admin\",spass == \"cetc52\" {" || body="rfid/content/superuser" || body="rfid/content/superuser" && body="if (suser==\"admin\",spass==\"cetc52\" {"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('if (suser == "admin" && spass == "cetc52" {') && response.body_string.contains("rfid/content/superuser")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('if suser == "admin",spass == "cetc52" {')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("rfid/content/superuser")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("rfid/content/superuser") && response.body_string.contains('if (suser=="admin",spass=="cetc52" {')
expression: r0() || r1() || r2() || r3()
