name: fingerprint-yaml-ChinaTelecomEquipmentWEBConfigurationSystem
manual: false
detail:
    fingerprint:
        name: ChinaTelecomEquipmentWEBConfigurationSystem
    fofa: body="设备web配置</font"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("设备web配置</font")
expression: r0()
