name: fingerprint-yaml-Cisco-Phone-Adapter-Configuration-Utility
manual: false
detail:
    fingerprint:
        name: Cisco-Phone-Adapter-Configuration-Utility
    fofa: body="login.cgi" && body="configuration utility" && body="cisco" || body="cisco" && body="configuration utility"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("login.cgi") && response.body_string.contains("configuration utility") && response.body_string.contains("cisco")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("cisco") && response.body_string.contains("configuration utility")
expression: r0() || r1()
