name: fingerprint-yaml-EMERSON-EnvironmentalEnergyMonitoringSystem
manual: false
detail:
    fingerprint:
        name: EMERSON-EnvironmentalEnergyMonitoringSystem
    fofa: body="alert(\"网络断连或者idu-s没有启动."
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('alert("网络断连或者idu-s没有启动.')
expression: r0()
