name: fingerprint-yaml-Enhydra-Application-Server
manual: false
detail:
    fingerprint:
        name: Enhydra-Application-Server
    fofa: header="enhydra" || header="Enhydra"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("enhydra"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Enhydra"))
expression: r0() || r1()
