name: fingerprint-yaml-Gzsa-Intranet-security
manual: false
detail:
    fingerprint:
        name: Gzsa-Intranet-security
    fofa: body="gzsa. all rights reserved</span>"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("gzsa. all rights reserved</span>")
expression: r0()
