name: fingerprint-yaml-Haoyun-Security
manual: false
detail:
    fingerprint:
        name: Haoyun-Security
    fofa: body="<span>浩云安防</span></div>"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<span>浩云安防</span></div>")
expression: r0()
