name: fingerprint-yaml-Hejia-Modularized&environment-Monitoring-system-of-Data-Center
manual: false
detail:
    fingerprint:
        name: Hejia-Modularized&environment-Monitoring-system-of-Data-Center
    fofa: body="content=\"www.hejia-tech.com" || title="和嘉科技-机房动力环境监控系统"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('content="www.hejia-tech.com')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("和嘉科技-机房动力环境监控系统")
expression: r0() || r1()
