name: fingerprint-yaml-Hikvision-Image-Recovery-Configuration
manual: false
detail:
    fingerprint:
        name: Hikvision-Image-Recovery-Configuration
    fofa: body="杭州海康威视数字技术股份有限公司"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("杭州海康威视数字技术股份有限公司")
expression: r0()
