name: fingerprint-yaml-Horde-Application-Framework
manual: false
detail:
    fingerprint:
        name: Horde-Application-Framework
    fofa: 'body="Powered by Horde" || body="<img src=\"/themes/default/graphics/horde-power1.png" || header="horde_secret_key" || body="title=\"This site is powered by The Horde Application Framework.\" href=\"http://horde.org\">" || body="Powered by </font><a href=\"http://www.horde.org/\" TARGET=_blank>" || body="<!-- IMP: Copyright 2001-2006, The Horde Project. IMP is under the GPL. -->" || body="<!--   Horde Project: http://horde.org/ | IMP: http://horde.org/imp/    -->" || body="/themes/graphics/horde-power1.png\" alt=\"Powered by Horde\" title=\"\" />" || body="if (typeof(_setHordeTitle) == \"undefined\",document.title,parent.frames.horde_main) parent.document.title = document.title;" || body="<!-- This file contains any \"Message Of The Day\" Type information -->" || body="<a href=\"icon_browser.php?app=chora\">Version Control</a><br />" || body="<html><body bgcolor=\"#aaaaaa\"><a href=\"icon_browser.php\">Application List</a><br /><br /><h2>Icons for My Account</h2>" || body="<script language=\"JavaScript\" type=\"text/javascript\" src=\"/hunter/js/enter_key_trap.js\"></script>" || body="<link href=\"/mail/mailbox.php?mailbox=INBOX\" rel=\"Top\" />"'
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("Powered by Horde")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<img src="/themes/default/graphics/horde-power1.png')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("horde_secret_key"))
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('title="This site is powered by The Horde Application Framework." href="http://horde.org">')
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('Powered by </font><a href="http://www.horde.org/" TARGET=_blank>')
    r5:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: 'response.body_string.contains("<!-- IMP: Copyright 2001-2006, The Horde Project. IMP is under the GPL. -->")'
    r6:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: 'response.body_string.contains("<!--   Horde Project: http://horde.org/ | IMP: http://horde.org/imp/    -->")'
    r7:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('/themes/graphics/horde-power1.png" alt="Powered by Horde" title="" />')
    r8:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('if (typeof(_setHordeTitle) == "undefined",document.title,parent.frames.horde_main) parent.document.title = document.title;')
    r9:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<!-- This file contains any "Message Of The Day" Type information -->')
    r10:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<a href="icon_browser.php?app=chora">Version Control</a><br />')
    r11:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<html><body bgcolor="#aaaaaa"><a href="icon_browser.php">Application List</a><br /><br /><h2>Icons for My Account</h2>')
    r12:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<script language="JavaScript" type="text/javascript" src="/hunter/js/enter_key_trap.js"></script>')
    r13:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<link href="/mail/mailbox.php?mailbox=INBOX" rel="Top" />')
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6() || r7() || r8() || r9() || r10() || r11() || r12() || r13()
