name: fingerprint-yaml-IBM WebSphere Application
manual: false
detail:
    fingerprint:
        name: IBM WebSphere Application
    fofa: header="IBM WebSphere Application" || title="IBM WebSphere Application"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("IBM WebSphere Application"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("IBM WebSphere Application")
expression: r0() || r1()
