name: fingerprint-yaml-IBM-WebSphere-Application-Server
manual: false
detail:
    fingerprint:
        name: IBM-WebSphere-Application-Server
    fofa: 'header="server: websphere application server"'
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: 'response.raw_header.bcontains(bytes("server: websphere application server"))'
expression: r0()
