name: fingerprint-yaml-ISPConfig
manual: false
detail:
    fingerprint:
        name: ISPConfig
    fofa: icon_hash="483383992" || body="powered by <a href=\"http://www.ispconfig.org" || body="powered by <a HREF=\"http://www.ispconfig.org" || body="This IP address is shared. For access to the web site which you look for, enter its address instead of its IP."
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: faviconHash(response.getIconContent()) == 483383992
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('powered by <a href="http://www.ispconfig.org')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('powered by <a HREF="http://www.ispconfig.org')
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("This IP address is shared. For access to the web site which you look for, enter its address instead of its IP.")
expression: r0() || r1() || r2() || r3()
