name: fingerprint-yaml-JiTon-Server-Room-environment-monitoring-system
manual: false
detail:
    fingerprint:
        name: JiTon-Server-Room-environment-monitoring-system
    fofa: body=" var ierrorcode = args.errorcode" || body="var ierrorcode = args.errorcode" || title="计通机房环境监控系统"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains(" var ierrorcode = args.errorcode")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("var ierrorcode = args.errorcode")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("计通机房环境监控系统")
expression: r0() || r1() || r2()
