name: fingerprint-yaml-Jurassic-Application-Management-System
manual: false
detail:
    fingerprint:
        name: Jurassic-Application-Management-System
    fofa: body="var _usermenusurl = '/appcenter/functions/getusermenu'" && body="jurassic" || body="jurassic" && body="var _usermenusurl = \"/appcenter/functions/getusermenu\"" || body="var _usermenusurl = \"/appcenter/functions/getusermenu\"" || body="jurassic" || body="var _usermenusurl = /appcenter/functions/getusermenu\""
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("var _usermenusurl = '/appcenter/functions/getusermenu'") && response.body_string.contains("jurassic")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("jurassic") && response.body_string.contains('var _usermenusurl = "/appcenter/functions/getusermenu"')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('var _usermenusurl = "/appcenter/functions/getusermenu"')
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("jurassic")
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('var _usermenusurl = /appcenter/functions/getusermenu"')
expression: r0() || r1() || r2() || r3() || r4()
