name: fingerprint-yaml-ManageEngine-Applications-Manager
manual: false
detail:
    fingerprint:
        name: ManageEngine-Applications-Manager
    fofa: 'body="/appmanager.js" || header="cookie: jsessionid_apm_9090" || header="ManageEngine Applications Manager" || body="<!-- This comment is for Instant Gratification to work applications.do -->" || body="<SCRIPT LANGUAGE=\"JavaScript1.2\" SRC=\"/template/appmanager.js\"></SCRIPT>" || body="<title>Applications Manager Login Screen</title>" || title="ManageEngine Applications Manager" || title="applications manager "'
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("/appmanager.js")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: 'response.raw_header.bcontains(bytes("cookie: jsessionid_apm_9090"))'
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("ManageEngine Applications Manager"))
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<!-- This comment is for Instant Gratification to work applications.do -->")
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<SCRIPT LANGUAGE="JavaScript1.2" SRC="/template/appmanager.js"></SCRIPT>')
    r5:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<title>Applications Manager Login Screen</title>")
    r6:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("ManageEngine Applications Manager")
    r7:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("applications manager ")
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6() || r7()
