name: fingerprint-yaml-Mission-Control-Application-Shield
manual: false
detail:
    fingerprint:
        name: Mission-Control-Application-Shield
    fofa: body="alt=\"mission control application shield" || body="<img id=\"logo\" src=\"/srm-error-pages/images/logo.gif\" alt=\"mission control application shield\" ></td><td><p class=\"notification\">Notification</p></td>" || title="Mission Control Application Shield"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('alt="mission control application shield')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<img id="logo" src="/srm-error-pages/images/logo.gif" alt="mission control application shield" ></td><td><p class="notification">Notification</p></td>')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Mission Control Application Shield")
expression: r0() || r1() || r2()
