name: fingerprint-yaml-MkDocs
manual: false
detail:
    fingerprint:
        name: MkDocs
    fofa: header="MkDocs" || title="MkDocs"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("MkDocs"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("MkDocs")
expression: r0() || r1()
