name: fingerprint-yaml-Netlify
manual: false
detail:
    fingerprint:
        name: Netlify
    fofa: header="Netlify" || title="Netlify"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Netlify"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Netlify")
expression: r0() || r1()
