name: fingerprint-yaml-ProdysWebServer
manual: false
detail:
    fingerprint:
        name: ProdysWebServer
    fofa: header="ProdysWebServer" || title="ProdysWebServer"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("ProdysWebServer"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("ProdysWebServer")
expression: r0() || r1()
