name: fingerprint-yaml-Prometheus Node Exporter
manual: false
detail:
    fingerprint:
        name: Prometheus Node Exporter
    fofa: header="Prometheus Node Exporter" || title="Prometheus Node Exporter"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Prometheus Node Exporter"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Prometheus Node Exporter")
expression: r0() || r1()
