name: fingerprint-yaml-Razuna Application Server
manual: false
detail:
    fingerprint:
        name: Razuna Application Server
    fofa: header="Razuna Application Server" || title="Razuna Application Server"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Razuna Application Server"))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("Razuna Application Server")
expression: r0() || r1()
