name: fingerprint-yaml-rconfig
manual: false
detail:
    fingerprint:
        name: rconfig
    fofa: body="rConfigLogo"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("rConfigLogo")
expression: r0()
