name: fingerprint-yaml-RuiJie-Application-Control-Engine
manual: false
detail:
    fingerprint:
        name: RuiJie-Application-Control-Engine
    fofa: body="window.open(\"/login.do\",\"airwin" || title="锐捷应用控制引擎"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('window.open("/login.do","airwin')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("锐捷应用控制引擎")
expression: r0() || r1()
