name: fingerprint-yaml-Sangfor-Application-Performance-Management
manual: false
detail:
    fingerprint:
        name: Sangfor-Application-Performance-Management
    fofa: body="help=\"版本信息:<br/>apm-" || title="sangfor apm"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('help="版本信息:<br/>apm-')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("sangfor apm")
expression: r0() || r1()
