name: fingerprint-yaml-Spring-Security
manual: false
detail:
    fingerprint:
        name: Spring-Security
    fofa: header="realm=\"spring security application" || header="Spring Security Application"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes('realm="spring security application'))
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("Spring Security Application"))
expression: r0() || r1()
