name: fingerprint-yaml-Swagger
manual: false
detail:
    fingerprint:
        name: Swagger
    fofa: body="<div id=\"swagger-ui\"></div>" || body="swagger-ui.css" && body="swagger-ui.js" || body="swagger-ui.js" || body="swagger-ui.css" || title="swagger ui"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('<div id="swagger-ui"></div>')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("swagger-ui.css") && response.body_string.contains("swagger-ui.js")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("swagger-ui.js")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("swagger-ui.css")
    r4:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("swagger ui")
expression: r0() || r1() || r2() || r3() || r4()
