name: fingerprint-yaml-Symantec-Client-Security
manual: false
detail:
    fingerprint:
        name: Symantec-Client-Security
    fofa: body="<!-- symantec client security web based installation -->"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("<!-- symantec client security web based installation -->")
expression: r0()
