name: fingerprint-yaml-Tongtech-application-server-TongWeb
manual: false
detail:
    fingerprint:
        name: Tongtech-application-server-TongWeb
    fofa: header="tongweb server"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.raw_header.bcontains(bytes("tongweb server"))
expression: r0()
