name: fingerprint-yaml-Topsec-WEB-application-firewall
manual: false
detail:
    fingerprint:
        name: Topsec-WEB-application-firewall
    fofa: body="evpng.fix('div, ul, img, li, input'; //evpng.fix('pngid1, pngid2'" || body="evpng.fix\"div, ul, img, li, input\"; //evpng.fix\"pngid1, pngid2\"" || title="天融信web应用防火墙"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("evpng.fix('div, ul, img, li, input'; //evpng.fix('pngid1, pngid2'")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('evpng.fix"div, ul, img, li, input"; //evpng.fix"pngid1, pngid2"')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("天融信web应用防火墙")
expression: r0() || r1() || r2()
