name: fingerprint-yaml-Topsec-Web-application-security-&-protection-system
manual: false
detail:
    fingerprint:
        name: Topsec-Web-application-security-&-protection-system
    fofa: body="class=\"logintop\"" && body="href=\"login_html_files/loginstyle.css\"" || body="href=\"login_html_files/loginstyle.css\"" || body="class=\"logintop\""
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('class="logintop"') && response.body_string.contains('href="login_html_files/loginstyle.css"')
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('href="login_html_files/loginstyle.css"')
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains('class="logintop"')
expression: r0() || r1() || r2()
