name: fingerprint-yaml-Venustech-TianQing-Application-Security-Gateway
manual: false
detail:
    fingerprint:
        name: Venustech-TianQing-Application-Security-Gateway
    fofa: body="v2/global/vendor/modernizr/modernizr.js" && body="天清web应用安全网关" || body="天清web应用安全网关" && body="v2/global/vendor/modernizr/modernizr.js" || body="v2/global/vendor/modernizr/modernizr.js" || body="天清web应用安全网关"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("v2/global/vendor/modernizr/modernizr.js") && response.body_string.contains("天清web应用安全网关")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("天清web应用安全网关") && response.body_string.contains("v2/global/vendor/modernizr/modernizr.js")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("v2/global/vendor/modernizr/modernizr.js")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("天清web应用安全网关")
expression: r0() || r1() || r2() || r3()
