name: fingerprint-yaml-Warcraft-3-Frozen-Throne-Mod-Config-File
manual: false
detail:
    fingerprint:
        name: Warcraft-3-Frozen-Throne-Mod-Config-File
    fofa: body="// Radius to give XP to teammates near where the special objective is completed (rescued hosties, bomb planted, killed vip, vip escaped, default is 750)"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("// Radius to give XP to teammates near where the special objective is completed (rescued hosties, bomb planted, killed vip, vip escaped, default is 750)")
expression: r0()
