name: fingerprint-yaml-Webapplicationdetectionsystem
manual: false
detail:
    fingerprint:
        name: Webapplicationdetectionsystem
    fofa: title="天镜web应用检测系统"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("天镜web应用检测系统")
expression: r0()
