name: fingerprint-yaml-Xbrother-Modularized&environment-Monitoring-system-of-Data-Center
manual: false
detail:
    fingerprint:
        name: Xbrother-Modularized&environment-Monitoring-system-of-Data-Center
    fofa: body="id=webclient codebase=webclient.cab" && body="classid=clsid:6892ebc7-0186-4a73-a5ce-a144865f3dc5>" || body="classid=clsid:6892ebc7-0186-4a73-a5ce-a144865f3dc5>" || body="id=webclient codebase=webclient.cab" || title="深圳市共济科技机房监控系统"
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("id=webclient codebase=webclient.cab") && response.body_string.contains("classid=clsid:6892ebc7-0186-4a73-a5ce-a144865f3dc5>")
    r1:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("classid=clsid:6892ebc7-0186-4a73-a5ce-a144865f3dc5>")
    r2:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.body_string.contains("id=webclient codebase=webclient.cab")
    r3:
        request:
            cache: true
            method: GET
            path: /
            follow_redirects: true
        expression: response.title_string.contains("深圳市共济科技机房监控系统")
expression: r0() || r1() || r2() || r3()
